export const EVENT_CATEGORIES = {
  Meeting: {
    key: "Meeting",
    label: "Meeting / Townhall",
    shortLabel: "Meeting",
    badgeClass: "bg-blue-50 text-blue-700 border-blue-200",
    dotClass: "bg-blue-500",
    borderClass: "border-blue-300",
    bgClass: "bg-blue-50/50",
    textClass: "text-blue-700",
    description: "Team syncs, town halls, 1-on-1s, and board meetings",
  },
  Leave: {
    key: "Leave",
    label: "Vacation / Planned Leave",
    shortLabel: "Vacation / Leave",
    badgeClass: "bg-amber-50 text-amber-700 border-amber-200",
    dotClass: "bg-amber-500",
    borderClass: "border-amber-300",
    bgClass: "bg-amber-50/50",
    textClass: "text-amber-700",
    description: "Annual leave, casual, sick leave, and employee time off",
  },
  Holiday: {
    key: "Holiday",
    label: "Public & Company Holiday",
    shortLabel: "Holiday",
    badgeClass: "bg-purple-50 text-purple-700 border-purple-200",
    dotClass: "bg-purple-500",
    borderClass: "border-purple-300",
    bgClass: "bg-purple-50/50",
    textClass: "text-purple-700",
    description: "National, gazetted, and company-declared holidays",
  },
  Fun: {
    key: "Fun",
    label: "Fun & Culture Activity",
    shortLabel: "Fun & Culture",
    badgeClass: "bg-pink-50 text-pink-700 border-pink-200",
    dotClass: "bg-pink-500",
    borderClass: "border-pink-300",
    bgClass: "bg-pink-50/50",
    textClass: "text-pink-700",
    description: "Team offsites, hackathons, birthday celebrations, socials & games",
  },
  Training: {
    key: "Training",
    label: "Training & Workshop",
    shortLabel: "Training",
    badgeClass: "bg-emerald-50 text-emerald-700 border-emerald-200",
    dotClass: "bg-emerald-500",
    borderClass: "border-emerald-300",
    bgClass: "bg-emerald-50/50",
    textClass: "text-emerald-700",
    description: "Skill workshops, compliance, bootcamps, and certifications",
  },
  HRMilestone: {
    key: "HRMilestone",
    label: "HR & Payroll Milestone",
    shortLabel: "HR Milestone",
    badgeClass: "bg-indigo-50 text-indigo-700 border-indigo-200",
    dotClass: "bg-indigo-500",
    borderClass: "border-indigo-300",
    bgClass: "bg-indigo-50/50",
    textClass: "text-indigo-700",
    description: "Payroll cutoffs, appraisal deadlines, probation reviews & benefits",
  },
  Company: {
    key: "Company",
    label: "Company Milestone",
    shortLabel: "Company Event",
    badgeClass: "bg-teal-50 text-teal-700 border-teal-200",
    dotClass: "bg-teal-500",
    borderClass: "border-teal-300",
    bgClass: "bg-teal-50/50",
    textClass: "text-teal-700",
    description: "Product launches, quarterly business reviews, investor days",
  },
};

export const DEPARTMENTS = [
  "All Staff",
  "Engineering",
  "Product",
  "Design",
  "HR & People Ops",
  "Finance",
  "Marketing",
  "Sales & Operations",
  "Executive Leadership",
];

export const DAYS_OF_WEEK = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];

export const MONTH_NAMES = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];
